# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre y Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('domicilio', models.CharField(max_length=500)),
                ('geo', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
    ]
