# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0002_auto_20171031_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='celular',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tel\xe9fono Celular'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='disponibilidad',
            field=models.TextField(default='', verbose_name='Disponibilidad Semanal'),
            preserve_default=False,
        ),
    ]
