# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0003_auto_20171031_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=150, verbose_name='Puesto')),
                ('direccion', models.CharField(max_length=250, verbose_name='Direcci\xf3n')),
                ('direccion_completa', models.CharField(max_length=350, verbose_name='Direcci\xf3n Completa')),
                ('geo', geoposition.fields.GeopositionField(max_length=42)),
                ('horario', models.TextField(verbose_name='Horario')),
                ('telefono', models.CharField(max_length=15, verbose_name='Tel\xe9fono')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre y Apellido')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('referencias', models.TextField(verbose_name='Referencias')),
            ],
        ),
        migrations.AddField(
            model_name='postulante',
            name='antecedentes',
            field=models.TextField(blank=True, verbose_name='Antecedentes'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='dni',
            field=models.CharField(default=12, max_length=8, verbose_name='DNI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulante',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=30, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='hijos',
            field=models.IntegerField(blank=True, default=99, verbose_name='Cantidad de hijos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulante',
            name='nacimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulante',
            name='nacionalidad',
            field=models.CharField(default='argentino', max_length=30, verbose_name='Nacionalidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulante',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='referencias',
            field=models.TextField(blank=True, verbose_name='Referencias'),
        ),
    ]
