# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0005_auto_20171102_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='edad',
        ),
        migrations.AddField(
            model_name='postulante',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto'),
        ),
    ]
