# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-04 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0006_auto_20171102_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fechaFin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalizaci\xf3n')),
                ('obsTrabajador', models.TextField(blank=True, null=True, verbose_name='Observaciones del Trabajador')),
                ('obsEmpleador', models.TextField(blank=True, null=True, verbose_name='Observaciones del Empleador')),
                ('obsNuestras', models.TextField(blank=True, null=True, verbose_name='Observaciones Nuestras')),
            ],
        ),
        migrations.AlterField(
            model_name='postulante',
            name='hijos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de hijos'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='empleador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleo.Puesto'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleo.Postulante'),
        ),
    ]
