# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-04 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0007_auto_20171104_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'verbose_name_plural': 'Asignaciones'},
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='trabajador',
        ),
    ]
